version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    container_name: noctura-couchdb
    restart: unless-stopped
    ports:
      - "${COUCHDB_PORT:-5984}:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ${COUCHDB_DATA_DIR:-./data/couchdb}:/opt/couchdb/data
      - ${COUCHDB_CONFIG_DIR:-./data/config}:/opt/couchdb/etc/local.d
    networks:
      - noctura-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  noctura-net:
    driver: bridge
